# Generated by Django 3.0.6 on 2020-05-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={},
        ),
    ]
