# Generated by Django 3.0.6 on 2020-05-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20200510_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={},
        ),
    ]
